export {IUser} from './user'
export {IProfile} from './profile'
export {IAnime} from './anime'
export {IAuth} from './auth'
export {IReview} from './review'
export {IError} from './error'
export {ILike} from './like'
export {IRating} from './rating'