const START_YEAR = 1917;
export const CURRENT_YEAR = new Date().getFullYear()
export const YEARS_ARRAY = Array.from({ length: CURRENT_YEAR - START_YEAR + 1 }, (_, i) => (START_YEAR + i).toString())

export const GENRES = [
    "action",
    "adventure",
    "cars",
    "comedy",
    "dementia",
    "demons",
    "drama",
    "ecchi",
    "fantasy",
    "game",
    "harem",
    "hentai",
    "historical",
    "horror",
    "josei",
    "kids",
    "magic",
    "martial arts",
    "mecha",
    "military",
    "music",
    "mystery",
    "parody",
    "police",
    "psychological",
    "romance",
    "samurai",
    "school",
    "sci-fi",
    "seinen",
    "shoujo",
    "shoujo ai",
    "shounen",
    "shounen ai",
    "slice of life",
    "space",
    "sports",
    "super power",
    "supernatural",
    "thriller",
    "vampire",
    "yaoi",
    "yuri"
  ]
  