# Generated by Django 4.1.3 on 2022-12-15 02:49

import AnimeServiceREST.api.helpers.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersmodel',
            name='username',
            field=models.CharField(max_length=25, unique=True, validators=[AnimeServiceREST.api.helpers.validators.only_letters_validator]),
        ),
    ]
