# Generated by Django 4.1.3 on 2022-12-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genremodel',
            name='anime',
        ),
        migrations.AddField(
            model_name='animemodel',
            name='genres',
            field=models.ManyToManyField(to='api.genremodel'),
        ),
    ]
