# Generated by Django 4.1.3 on 2022-12-17 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_genremodel_anime_animemodel_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='animemodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
