# Generated by Django 4.1.3 on 2022-12-21 11:22

import AnimeServiceREST.api.helpers.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_profile_birthday_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersmodel',
            name='user_tag',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='usersmodel',
            name='username',
            field=models.CharField(max_length=25, validators=[AnimeServiceREST.api.helpers.validators.only_letters_validator]),
        ),
    ]
