# Generated by Django 4.1.3 on 2022-12-22 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_usersmodel_user_tag_alter_usersmodel_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersmodel',
            name='user_tag',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='usersmodel',
            unique_together={('username', 'user_tag')},
        ),
    ]
