# Generated by Django 4.1.6 on 2023-03-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_usersmodel_user_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animemodel',
            name='likes',
            field=models.JSONField(default=[]),
        ),
        migrations.AddField(
            model_name='animemodel',
            name='rating',
            field=models.JSONField(default=[]),
        ),
    ]
