# Generated by Django 4.1.6 on 2023-03-29 03:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_animemodel_likes_alter_animemodel_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animemodel',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='animemodel',
            name='rating',
        ),
        migrations.CreateModel(
            name='AnimeStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(blank=True, default=None, null=True)),
                ('rating', models.FloatField(blank=True, default=None, null=True)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.animemodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
