# Generated by Django 4.1.6 on 2023-03-29 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_animemodel_likes_remove_animemodel_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animestats',
            name='rating',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
